### ISSUE TITLE
Incorrect request

### ISSUE THREAD

**Issue by Qadronic** [zeviel/anixart.py#3]
В [search_profile()](https://github.com/zeviel/anixart.py/blob/main/src/anixart.py#L441) функции Вы должны делать реквест через json, а не data. Более того, лучше бы везде так писать, ибо аниксарт требует именно Content-Type=application/json в запросах.
Пофиксите хотя бы [это](https://github.com/zeviel/anixart.py/blob/main/src/anixart.py#L448), пожалуйста.

**Comment by vraestoren** [comment]
```python
headers = {"content-type": "application/json"}
``` 
Библиотека не обновлялась 7 месяцев, не будь ленивым и фикси сам , до этого все прекрасно работало. А если не можешь в чем я уверен после того как ты сказал мне заменить все строки с data=data на json=data вместо того чтобы добавить нужный параметр в заголовок запроса то выкинь свой пк (если у тебя он хотя бы был в жизни) из окна вместе с собой так как ты не способен добавить одну линию строки что означает о твоих низких способностях думать ведь ты даже не смог написать где именно Content-Type=application/json требуется в запросах (header - заголовок) оскверняя русский язык английскими словами такого рода как: пофиксить, реквест а ещё функции это множественное число где ты его увидел в функциЙ search_profile не понимаю😁 Даже создав данную незначимую проблему в этом репозиторий с одним из глупейших обьяснений ты умудрился пернуть с коричневой подливой вылетающей словно высоконапорная отрыжка из твоего заднего отверстия.

**Comment by Qadronic** [comment]
Вы уж меня извините, если чем-то обидел, но придираться к словам - это низко, когда я вас просто и спокойно попросил "исправить" ошибку. Естественно я уже всё сделал, что мне было нужно и просто решил поделиться с Вами проблемой. Зачем вы начали меня оскорблять?
